export const taskListMock = [
  {
    descricao: "",
    id: "01",
    image: "",
    priority: "high",
    progress: 0,
    status: "To Do",
    title: "Go to gym",
  },
  {
    descricao: "",
    id: "02",
    image: "",
    priority: "low",
    progress: 100,
    status: "Done",
    title: "Read a book",
  },
]

export const taskListMock2 = [
  {
    descricao: "",
    id: "01",
    image: "",
    priority: "high",
    progress: 0,
    status: "To Do",
    title: "Go to gym",
  },
  {
    descricao: "",
    id: "02",
    image: "",
    priority: "low",
    progress: 100,
    status: "Done",
    title: "Read a book",
  },
  {
    descricao: "",
    id: "03",
    image: "",
    priority: "medium",
    progress: 50,
    status: "In Progress",
    title: "Go to market",
  },
  {
    descricao: "",
    id: "04",
    image: "",
    priority: "high",
    progress: 0,
    status: "To Do",
    title: "Restart Learning Solidworks",
  },
  {
    descricao: "",
    id: "05",
    image: "",
    priority: "high",
    progress: 100,
    status: "Done",
    title: "change slider to scroll",
  },
  {
    descricao: "",
    id: "06",
    image: "",
    priority: "medium",
    progress: 50,
    status: "In Progress",
    title: "To publish the article",
  },
]
