export const taskListMock = [
  {
    description: "Do something",
    id: "01",
    image: "",
    priority: "high",
    progress: 0,
    status: "To Do",
    title: "Go to gym",
  },
  {
    description: "I love read books",
    id: "02",
    image: "",
    priority: "low",
    progress: 100,
    status: "Done",
    title: "Read a book",
  },
  {
    description: "",
    id: "03",
    image: "",
    priority: "low",
    progress: 100,
    status: "Done",
    title: "Lets go!",
  },
]

export const taskListMock2 = [
  {
    description: "Do something II",
    id: "01",
    image: "",
    priority: "high",
    progress: 0,
    status: "To Do",
    title: "Go to gym",
  },
  {
    description: "I love read",
    id: "02",
    image: "",
    priority: "low",
    progress: 100,
    status: "Done",
    title: "Read a book",
  },
  {
    description: "I need go to the market",
    id: "03",
    image: "",
    priority: "medium",
    progress: 50,
    status: "In Progress",
    title: "Go to market",
  },
  {
    description: "Need to study",
    id: "04",
    image: "",
    priority: "high",
    progress: 0,
    status: "To Do",
    title: "Restart Learning Solidworks",
  },
  {
    description: "Slider example",
    id: "05",
    image: "",
    priority: "high",
    progress: 100,
    status: "Done",
    title: "change slider to scroll",
  },
  {
    description: "Soh hard soh far",
    id: "06",
    image: "",
    priority: "medium",
    progress: 50,
    status: "In Progress",
    title: "To publish the article",
  },
]
